try:
    result = 45/0
except:
    print("Error found")
finally:
    print("All done")
